version: '3.0'
services:
  python:
    image: python:3.8-slim
  java:
    image: openjdk:8-jdk-slim
  lpr_master_node:
    container_name: lpr-master-node
    image: takeruadelbert/lpr-master-node
    command: java -jar lpr-master-node-0.0.1.war -m http.server 7070
    ports:
      - 7070:7070
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - environment.env
    network_mode: "host"