spring:
  kafka:
    bootstrap-servers: ${KAFKA_HOST:192.168.88.201}:${KAFKA_PORT:9092}
kafka:
  host: ${KAFKA_HOST:192.168.88.201}
  port: ${KAFKA_PORT:9092}
  topic:
    input-frame: ${KAFKA_CONSUME_TOPIC_INPUT_FRAME:LPRResult}
    input-image: ${KAFKA_CONSUME_TOPIC_INPUT_IMAGE:LPRImageServiceResult}
  group: ${KAFKA_CONSUME_TOPIC_GROUP_ID:lpr-service-result}
client:
  base-url: ${BASE_URL}