version: '2'
services:
  nginx:
    image: nginx:1.17.3
    restart: always
    ports:
      - 443:443
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./deployment/nginx.ssl.conf:/etc/nginx/nginx.ssl.conf
      - ./deployment/plain.nginx.conf:/etc/nginx/conf.d/http.conf
      - ./deployment/dhparam.pem:/etc/nginx/dhparam.pem
      - ./ssl.crt:/etc/nginx/ssl.crt
      - ./ssl.key:/etc/nginx/ssl.key
      - ./client:/client
    depends_on:
      - main

  main:
    restart: always
    command: java -jar app.war
    image: openjdk:8-jdk-alpine
    working_dir: /app
    volumes:
      - ./app.war:/app/app.war
    expose:
      - "8080"
    env_file:
      - .env
